# Generated by Django 5.0.1 on 2024-05-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalpost_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goalpostuser',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
    ]
